### PR TITLE
chore: Bump version to 0.28 for ratatui

### PR DESCRIPTION
**Pull request by orhun**
🧀

### CODE REVIEW

**Comment by uttarayan21** [comment]
Really sorry about the delay I somehow missed the notification about this.

**Comment by uttarayan21** [comment]
I published version v6.0.0

Also would you like to move this crate under the ratatui org ?
I'll help out if there are any major changes.
I've been very busy recently and often miss the ratatui releases.

**Comment by orhun** [comment]
> I published version v6.0.0

Perfect, thanks!

> Also would you like to move this crate under the ratatui org ?

Sounds good, you can either try the "Transfer ownership" action in the repository settings or add me to the repo and I can move it to github.com/ratatui :)

**Comment by uttarayan21** [comment]
I tried the "Transfer ownership" in github settings but that failed so I invited you as a collaborator.

**Comment by orhun** [comment]
I didn't get the invite, can you send it again? (@orhun)

**Comment by uttarayan21** [comment]
I sent it again. I think I might have missed something the last time.

**Comment by orhun** [comment]
got it!

**Comment by orhun** [comment]
I think you need to change my role to admin - I can't view the repository settings right now.

**Comment by uttarayan21** [comment]
Screenshot 2024-09-04 at 12 50 51 PM
I'm not sure how to do that. 
I don't think I can do that on a personal repo. That setting is in orgs only I think.

**Comment by orhun** [comment]
Ah, you can simply select me and change the "Type" on the top right I reckon.

**Comment by uttarayan21** [comment]
IMG_0218
Its just for filtering

**Comment by joshka** [comment]
To do this requires transferring it to someone with access to the ratatui org (danger zone on the general settings page) and then having them transfer the repo to ratatui

**Comment by orhun** [comment]
Yup, I think you need to somehow transfer the repository to me first. Then I can move it to ratatui org and give you access.

**Comment by orhun** [comment]
can you try again?

**Comment by uttarayan21** [comment]
Yeah I just initiated the transfer

**Comment by uttarayan21** [comment]
I also sent an invite in crates.io page for this.

**Comment by orhun** [comment]
Just moved the repo to the organization, can you check if you still have permissions etc.?

**Comment by uttarayan21** [comment]
IMG_0220
This is what I see

**Comment by orhun** [comment]
how about now?

**Comment by uttarayan21** [comment]
Yes now I have access to it.

**Pull request merged**
