### PR TITLE
Test with assertions

### PR DESCRIPTION
**Pull request by sayanarijit**
Tests with assertions and some hacky workaround for an old bug.

### CODE REVIEW

**Comment by sayanarijit** [comment]
@uttarayan21 only one test is failing. I'll probably need your help here.

**Comment by uttarayan21** [comment]
Seems like a  bug in the parse logic,
I wrote most of the logic on a single night so its gotten pretty convoluted.
I'm thinking of using [nom](docs.rs/nom) parsers to rewrite the logic but thats going to take a while since I'm learning how to use that.

**Comment by sayanarijit** [comment]
Or maybe use something like this https://docs.rs/ansi-parser ?

**Comment by uttarayan21** [comment]
Yeah I already looked into that crate when making this one but that doesn't handle colors and seems mostly for a live terminal instead of text.

**Comment by sayanarijit** [comment]
I made it work with some hacky workaround, which I think should be fine, until we learn to proper parsing.

**Comment by sayanarijit** [comment]
Forgot to remove `main`. Pushed again.

**Comment by sayanarijit** [comment]
@uttarayan21 could you have a a look?

**Pull request merged**
